// <auto-generated />
using System;
using Concretos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concretos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230427023708_EnableUser")]
    partial class EnableUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concretos.Models.Ecuation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FabricationMethodId")
                        .HasColumnType("int");

                    b.Property<int>("ReactiveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FabricationMethodId");

                    b.HasIndex("ReactiveId");

                    b.ToTable("Ecuations");
                });

            modelBuilder.Entity("Concretos.Models.FabricationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FabricationMethods");
                });

            modelBuilder.Entity("Concretos.Models.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Consecutive")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("DifferencePercentage")
                        .HasColumnType("real");

                    b.Property<float>("ExpectedDensity")
                        .HasColumnType("real");

                    b.Property<float>("ExpectedResistence")
                        .HasColumnType("real");

                    b.Property<DateTime>("ExperimentalDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("ExperimentalDensity")
                        .HasColumnType("real");

                    b.Property<float>("ExperimentalPorosity")
                        .HasColumnType("real");

                    b.Property<float>("ExperimentalResistence")
                        .HasColumnType("real");

                    b.Property<int>("FabricationMethodId")
                        .HasColumnType("int");

                    b.Property<int>("ReactiveId")
                        .HasColumnType("int");

                    b.Property<int>("StudyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FabricationMethodId");

                    b.HasIndex("ReactiveId");

                    b.HasIndex("StudyId");

                    b.ToTable("Measures");
                });

            modelBuilder.Entity("Concretos.Models.Reactive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reactives");
                });

            modelBuilder.Entity("Concretos.Models.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("Concretos.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enable")
                        .HasColumnType("bit");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Concretos.Models.Ecuation", b =>
                {
                    b.HasOne("Concretos.Models.FabricationMethod", "FabricationMethod")
                        .WithMany()
                        .HasForeignKey("FabricationMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concretos.Models.Reactive", "Reactive")
                        .WithMany()
                        .HasForeignKey("ReactiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FabricationMethod");

                    b.Navigation("Reactive");
                });

            modelBuilder.Entity("Concretos.Models.Measure", b =>
                {
                    b.HasOne("Concretos.Models.FabricationMethod", "FabricationMethod")
                        .WithMany()
                        .HasForeignKey("FabricationMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concretos.Models.Reactive", "Reactive")
                        .WithMany()
                        .HasForeignKey("ReactiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concretos.Models.Study", "Study")
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FabricationMethod");

                    b.Navigation("Reactive");

                    b.Navigation("Study");
                });

            modelBuilder.Entity("Concretos.Models.Study", b =>
                {
                    b.HasOne("Concretos.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
